### ISSUE TITLE
Add a `/register` route

### ISSUE THREAD

**Issue by mooocer** [hackSocIndore/hackSocIndore.github.io#12]
- We need a `/register` route that points to the latest event's registration form (or either has a form embedded in it).
- When there's an upcoming event that is announced, the page should show the appropriate message
- Feel free to propose any other ideas

**Comment by vbvh98** [comment]
It's better to use form embed because we dont have any server to create a route, while a register.html can be added with latest registration form embedded there.

**Comment by mooocer** [comment]
@harshmandalgi any comments?
@vbhv98 I agree. You may claim this issue, assign it to yourself and start if @harshmandalgi agrees.

**Comment by keshavlikhar** [comment]
Or we can just a link to google forms through a register button where user  can check which event they want to register

**Comment by mooocer** [comment]
@harshitlikhar No, we needed a link which we could use in a poster QR code and links on other places.

**Comment by mooocer** [comment]
@vbhv98 Next time you submit a pull request, don't forget to use the `fixes` keyword to automatically close the related issue. Close this issue when you have read my comment.
