### ISSUE TITLE
Footer needs to be enhanced

### ISSUE THREAD

**Issue by harry-hov** [hackSocIndore/hackSocIndore.github.io#23]
Current footer is too simple. It can improved by adding some social platform links and by improving little CSS.

**Comment by mooocer** [comment]
The issue didn't get closed automatically despite using the 'Fixes' keyword. I think that this has to do with using lowercase.
> fixes #23

In the future, when typing the keyword, make sure to select the option in the dropdown to ensure that you have used it correctly.

Close this issue once you've read it.
