### ISSUE TITLE
Revamp event section

### ISSUE THREAD

**Issue by indraasura** [hackSocIndore/hackSocIndore.github.io#29]
**Describe the feature you'd like**
*The events section, which is currently in the header section as a slider will look better if it is given a separate section and the events are organized into cards. The upcoming events will be arranged as cards and past events as a slider below the card section*

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Before you post, make sure you have:**
- [ ] assigned yourself to the issue if you want to work on it
- [x] added the correct labels to the issue

**Comment by mooocer** [comment]
@indraasura looks like you edited all the issue comment by mistake. Please put it back there :)
