### ISSUE TITLE
Navbar Toggle

### ISSUE THREAD

**Issue by amansohani222** [hackSocIndore/hackSocIndore.github.io#30]
**Describe the feature you'd like**
*A clear and concise description of what you want to happen.*
Navbar toggle will help user to track on which section of page he is and as scroll is instantaneous, so smooth scroll will improve UI.

**Wireframe / Mockup / Rough drawing / Screenshot**  
*If applicable, we would request you to provide a wireframe, mockup, rough drawing, or of some website that has this feature (if possible)*

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Before you post, make sure you have:**
- [x] assigned yourself to the issue if you want to work on it
- [ ] added the correct labels to the issue

**Comment by mooocer** [comment]
@amansohani222 can't see the use of this issue. Hasn't it been already solved by the PR you had opened?

**Comment by amansohani222** [comment]
Actually Navbar Toggling was not added earlier

**Comment by mooocer** [comment]
Alright then please remove 'Smooth scroll' as it's already done, and also would like to emphasize that the checkboxes on issue template are added for our ease, please make sure that they are checked as applicable.

**Comment by amansohani222** [comment]
Ok sure
