### ISSUE TITLE
Names of some contributors are missing

### ISSUE THREAD

**Issue by mooocer** [hackSocIndore/hackSocIndore.github.io#37]
**Describe the current behavior**  
Currently, only 4 people have been attributed in the footer.

**Describe the expected behavior**  
All the contributors should be attributed.

**How do we reproduce the issue**  
Scroll down to the footer section and see for yourselves. Click on the contributors' tab on the repo to find the profiles of all the contributors.

**Screenshots**  
No need

**Other info / logs**
Not Applicable

**Would you like to work on the issue?**
- [ ] Yes
- [x] No

**Before you post, make sure you have:**
- [ ] assigned yourself to the issue if you want to work on it
- [x] added the correct labels to the issue

**Comment by indraasura** [comment]
I am working on it
